title:              shawn Blog
email:              eogkr.kim@gmail.com
description:        A Blog Theme by Start Bootstrap
author:             Kim Seongsu
baseurl:            ""
url:                "https://shawn365.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    shawn365
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:
codepen_username: shawn365

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
